#!/bin/sh

# Obtém a lista de arquivos C# modificados no índice (staged)
files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.cs$')

# Se não houver arquivos C# modificados, sai do hook
if [ -z "$files" ]; then
  exit 0
fi

# Formata os arquivos estão formatados corretamente
echo "Verificando formatação dos arquivos modificados..."
dotnet format DuckStore.sln --include $files

git add $files

# Continua com o commit se todos os arquivos estiverem formatados
exit 0
