#!/bin/sh

# Obtém a lista de arquivos C# modificados no índice (staged)
files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.cs$')

# Se não houver arquivos C# modificados, sai do hook
if [ -z "$files" ]; then
  exit 0
fi

# Verifica se os arquivos estão formatados corretamente
echo "Verificando formatação dos arquivos modificados..."
dotnet format DuckStore.sln --include $files --verify-no-changes

# Verifica o código de saída do comando anterior
if [ $? -ne 0 ]; then
  echo "Erro: O código não está formatado corretamente. Execute 'dotnet format' e 'git add' novamente para corrigir."
  exit 1
fi

# Continua com o commit se todos os arquivos estiverem formatados
exit 0