@Ordering = https://localhost:5053/orders

### Get all orders
GET {{Ordering}}
Accept: application/json

### Get paginated orders
GET {{Ordering}}?PageIndex=0&PageSize=4
Accept: application/json

### Get orders by customer ID
GET {{Ordering}}/customer/58c49479-ec65-4de2-86e7-033c546291aa
Accept: application/json

### Get order by order number
GET {{Ordering}}/ORD_1
Accept: application/json

### Delete an order by ID
DELETE {{Ordering}}/1
Accept: application/json

### Update an order by ID
PUT {{Ordering}}/1
Content-Type: application/json
Accept: application/json

{
    "id": 1,
    "customerId": 1,
    "orderDate": "2023-10-01T00:00:00Z",
    "status": "Shipped",
    "totalAmount": 100.00
}
