namespace BuildingBlocks.Messaging.Events;

public record BasketCheckoutEvent : IntegrationEvent
{
    public string OwnerId { get; set; } = default!;
    public Guid CustomerId { get; set; }
    public decimal TotalPrice { get; set; }

    // Generated by Basket.Function at checkout time (see ADR-0038) — the single correlation id
    // Ordering uses as the Order's own identity and Payment uses to tag its Payment row, so both
    // aggregates key off the same value instead of each minting their own.
    public Guid OrderId { get; set; }

    // Opaque pass-through, chosen by the customer in the cart and carried verbatim to Payment
    // (ADR-0046 §6) — Basket never validates, interprets or computes anything about it, the same
    // way it never interprets TotalPrice or the card fields below. Null when no coupon was applied.
    public string? DiscountId { get; set; }

    public BasketCheckoutAddress ShippingAddress { get; set; } = new();
    public BasketCheckoutPayment Payment { get; set; } = new();
    public List<BasketCheckoutItem> Items { get; set; } = [];
}

public record BasketCheckoutAddress
{
    public string FirstName { get; set; } = default!;
    public string LastName { get; set; } = default!;
    public string EmailAddress { get; set; } = default!;
    public string AddressLine { get; set; } = default!;
    public string Country { get; set; } = default!;
    public string State { get; set; } = default!;
    public string ZipCode { get; set; } = default!;
}

public record BasketCheckoutPayment
{
    public string CardName { get; set; } = default!;
    public string CardNumber { get; set; } = default!;
    public string Expiration { get; set; } = default!;
    public string Cvv { get; set; } = default!;
    public int PaymentMethod { get; set; }
    public int Installments { get; set; }
}

public record BasketCheckoutItem(Guid ProductId, string ProductName, string? ImageId, int Quantity, decimal Price);
