<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>eb61cbad-73f7-4e52-aa17-af654518ba3c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AWS" />
    <PackageReference Include="Aspire.Hosting.Elasticsearch" />
    <PackageReference Include="Aspire.Hosting.NodeJs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Services\Basket\Basket.Function\Basket.Function.csproj" />
    <ProjectReference Include="..\Services\Basket\Basket.DevelopmentDataSeeder\Basket.DevelopmentDataSeeder.csproj" />
    <ProjectReference Include="..\Services\Catalog\Catalog.Function\Catalog.Function.csproj" />
    <ProjectReference Include="..\Services\Ordering\Ordering.Function\Ordering.Function.csproj" />
    <ProjectReference Include="..\Services\Catalog\Catalog.DevelopmentDataSeeder\Catalog.DevelopmentDataSeeder.csproj" />
    <ProjectReference Include="..\Services\Ordering\Ordering.DevelopmentDataSeeder\Ordering.DevelopmentDataSeeder.csproj" />
    <ProjectReference Include="..\Services\Payment\Payment.Function\Payment.Function.csproj" />
    <ProjectReference Include="..\Services\Payment\Payment.DevelopmentDataSeeder\Payment.DevelopmentDataSeeder.csproj" />
    <ProjectReference Include="..\Services\PaymentGateway\PaymentGateway.Function\PaymentGateway.Function.csproj" />
    <ProjectReference Include="..\Services\Pricing\Pricing.Function\Pricing.Function.csproj" />
    <ProjectReference Include="..\Services\Pricing\Pricing.DevelopmentDataSeeder\Pricing.DevelopmentDataSeeder.csproj" />
    <ProjectReference Include="..\Services\CatalogView\CatalogView.Function\CatalogView.Function.csproj" />
    <ProjectReference Include="..\Services\CatalogView\CatalogView.DevelopmentDataSeeder\CatalogView.DevelopmentDataSeeder.csproj" />
    <ProjectReference Include="..\Services\Review\Review.Function\Review.Function.csproj" />
    <ProjectReference Include="..\Services\Review\Review.DevelopmentDataSeeder\Review.DevelopmentDataSeeder.csproj" />
    <ProjectReference Include="..\Services\User\User.Function\User.Function.csproj" />
    <ProjectReference Include="..\Services\User\User.DevelopmentDataSeeder\User.DevelopmentDataSeeder.csproj" />
    <ProjectReference Include="..\WebApps\Managment.Web.Blazor\Managment.Web.Blazor.csproj" />
  </ItemGroup>

  <Target Name="RestoreNpm" BeforeTargets="Build" Condition=" '$(DesignTimeBuild)' != 'true' ">
    <ItemGroup>
      <PackageJsons Include="..\WebApps\*\package.json" />
    </ItemGroup>

    <!-- Install npm packages if node_modules is missing -->
    <Message Importance="Normal" Text="Installing npm packages for %(PackageJsons.RelativeDir)" Condition="!Exists('%(PackageJsons.RootDir)%(PackageJsons.Directory)/node_modules')" />
    <Exec Command="pnpm install" WorkingDirectory="%(PackageJsons.RootDir)%(PackageJsons.Directory)" Condition="!Exists('%(PackageJsons.RootDir)%(PackageJsons.Directory)/node_modules')" />
  </Target>

</Project>
