<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" />
    <PackageReference Include="Amazon.Lambda.RuntimeSupport" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ordering.Application\Ordering.Application.csproj" />
    <ProjectReference Include="..\Ordering.Infrastructure\Ordering.Infrastructure.csproj" />
  </ItemGroup>

</Project>
