global using System.Net;
global using BuildingBlocks.Pagination;
global using BuildingBlocks.ServiceDefaults;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.RazorPages;
global using Shopping.Web.Server.Models.Basket;
global using Shopping.Web.Server.Models.Catalog;
global using Shopping.Web.Server.Models.Ordering;
global using Shopping.Web.Server.Services;